#!/bin/sh

if [ ! -e ${HOME}/.vim/bundle/Vundle.vim ]; then
    git clone https://github.com/gmarik/Vundle.vim.git ${HOME}/.vim/bundle/Vundle.vim
fi
vim -u ${HOME}/.vimrc.bundles +PluginInstall +PluginClean! +qa

# Check for YCM installation
if [ -e ${HOME}/.vim/bundle/YouCompleteMe ] && \
   [ ! -f ${HOME}/.vim/bundle/YouCompleteMe/third_party/ycmd/ycm_client_support.so ]; then
    echo "Now would be a good time to compile YCM client support!"
    echo "pushd ~/.vim/bundle/YouCompleteMe && ./install.sh && popd"
fi
